Creates interface to compare metadata file with directory of dig objects.
VTUL/dlp-access pull request #364
Opened 2022-10-12 15:51 UTC by whunter

**Creates interface to compare metadata file with directory of digital objects and produce report.**
* * *

**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2622) (:star:)

* Other Relevant Links (Meeting note, project page, related pull requests, etc.)

# What does this Pull Request do? (:star:)
Creates interface to compare metadata file with directory of digital objects and produce report.

# What's the changes? (:star:)
A in-depth description of the changes made by this PR. Technical details and possible side effects.

* Checks if metadata records are valid and contain required fields `Identifier`, `Title`
* Provides list of identifiers found in metadata file and the digital objects that are associated with them in the local directory
* Provides list of identifiers that DO NOT have any digital objects associated with them (likely in error)

# How should this be tested?

This PR is difficult to test. To test you will either need to:
* create a directory containing digital objects and a custom metadata csv that describes these objects 
* (or)
* download a partial collection from S3 that already includes a metadata csv that describes it. The problem is that this collection is **_really big_** (despite it being only a subset of the actual collection) It can be downloaded like this: `aws s3 cp s3://lee-ingest-testing/SWVA/BTR <YourLocalFolder> --recursive` 
* Then, visit `/siteAdmin/pre-ingest-check`
* Upload metadata csv (if you download the S3 collection it's `BTR.csv`
* Select the `BTR/` directory, click "Upload," and then confirm
* Check that the report is accurate

# Additional Notes:
Any additional information that you think would be helpful when reviewing this PR.

* branch: `LIBTD-2622`

# Interested parties
@yinlinchen 

(:star:) Required fields

2022-10-18 19:33 UTC, andreaWaldren commented on src/pages/admin/ingestTools/PreIngestCheck.js
> +        ignoreFiles.indexOf(file.name) == -1 &&
I'd probably change this to ===

2022-10-18 19:35 UTC, andreaWaldren commented on src/css/adminForms.scss
> +#invalid-records > .invalid-record {
Maybe add "display: block" so each one shows up on a new line?

2022-10-18 19:38 UTC, andreaWaldren requested changes
I think this should be ok to approve after the push to delete the unused cryptoJS package and possibly adding some sort of navigation from this form to the other parts of the admin site. Great work overall!

2022-10-21 19:10 UTC, andreaWaldren approved these changes

2023-01-25 16:52 UTC, whunter commented on src/css/adminForms.scss
> +#invalid-records > .invalid-record {
👍

2023-01-27 19:10 UTC, merged